version: '2'

services:
  centos:
    restart: always
    image: centos/systemd
    ports:
    - "80:80/tcp"
    - "3306:3306/tcp"
    privileged: true
    volumes:
    - .:/opt/tmp
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
